### ISSUE TITLE
ubuntu16.04 无法运行

### ISSUE THREAD

**Issue by wangwenbin1991** [239573049/ChatGpt.Desktop#19]
因ubuntu16最高只支持到.net 6.0版本，而程序依赖7.0版本的，希望能加上这个版本的支持，感谢

**Comment by 239573049** [comment]
docker下也无法使用吗？

**Comment by wangwenbin1991** [comment]
明白，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月3日(周一) 晚上9:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [239573049/ChatGpt.Desktop] ubuntu16.04 无法运行 (Issue #19)




 
使用docker应该可以跨平台，建议尝试一下
