### ISSUE TITLE
取回答案时渲染有问题

### ISSUE THREAD

**Issue by Deson621** [239573049/ChatGpt.Desktop#21]
![d5e59572fdf41044f9ec8f383557e96](https://user-images.githubusercontent.com/7531186/229344822-d51cc12e-6a9b-48d9-ab44-fe24efc63cda.png)

取回答案会出现文字出现缺失或缺少的情况..希望Token大佬,能尽快帮忙修复一下..麻烦啦

**Comment by 239573049** [comment]
目前解决方案
增加设置系统角色


你有文字洁癖，你很喜欢写markdown格式的文字，任何一段文本你都会写成完美的markdown文本，每一个代码块还会标注该代码的语言。

**Comment by 239573049** [comment]
更新了masa blazor版本已经修复
