### ISSUE TITLE
复制小按钮可以不可以提到对话框外面

### ISSUE THREAD

**Issue by pty819** [239573049/ChatGpt.Desktop#24]
![06a2bf0e3abef8d8e35faaaa0407298](https://user-images.githubusercontent.com/14341805/230262934-fcd6545b-c99e-4527-a42b-de0ce787dd1a.png)

复制小按钮的位置总会挡住一个字符。。。

**Comment by 239573049** [comment]
已提高复制按钮高度，不遮挡文字
