### ISSUE TITLE
关于程序中默认调用的 ApiURL

### ISSUE THREAD

**Issue by pankejia2000** [239573049/ChatGpt.Desktop#3]
http://server.tokengo.top:1800/v1/chat/completions
这个地址是？

**Comment by 239573049** [comment]
> http://server.tokengo.top:1800/v1/chat/completions 这个地址是？

这个是提供不需要翻墙的api

**Comment by 239573049** [comment]
> http://server.tokengo.top:1800/v1/chat/completions 这个地址是？

可以替换成官方的api
