### ISSUE TITLE
返回的内容能直接返回markdown原格式吗？

### ISSUE THREAD

**Issue by dotnet9** [239573049/ChatGpt.Desktop#5]
感谢作者提供这么好的工具，使用体验非常好。

有个建议如标题。

## 问题描述

下面是我的搜索结果：

![image](https://user-images.githubusercontent.com/19390373/225344840-e1d3f99a-cb12-4594-b0f1-c4c53c45ed60.png)

结果是以渲染好的形式展示，我在查找相关的资料，有时是为了写总结出文，期望返回的是Markdown原格式，方便自己的网站二次渲染，虽然本工具提供右键复制，但有时我又希望只复制部分，目前只能右键全文复制。

## 建议

1. 原文与Markdown格式切换展示；
2. 左键部分文字选择复制。

**Comment by 239573049** [comment]
> 2\. 选择

增加动态 更换渲染格式
