### ISSUE TITLE
无法连接服务器

### ISSUE THREAD

**Issue by LHTXQ** [239573049/ChatGpt.Desktop#6]
能打开网页，但用这个软件填入apiKey后不行。
![image](https://user-images.githubusercontent.com/38943319/226299261-8739717e-5c52-4761-b6b0-c9e226958c63.png)

**Comment by 239573049** [comment]
是否可以截图查看设置的参数

**Comment by LHTXQ** [comment]
不可以，电脑没在身边。除了token，其他都是默认的，token那填的APIKey。
建议增加temper等更多参数设置，还有支持stream。



发件人: ***@***.***>
发送时间: 2023年3月20日 17:31
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [239573049/ChatGpt.Desktop] 无法连接服务器 (Issue #6)


是否可以截图查看设置的参数

―

**Comment by 239573049** [comment]
我看了异常信息，你这个应该是老版本的，建议更新一下版本

**Comment by 239573049** [comment]
版本更换
